name: Check branch name
on:
  pull_request:
    branches: [main]

jobs:
  check-branch-name:
    runs-on: ubuntu-latest
    steps:
      - uses: deepakputhraya/action-branch-name@master
        # linear numering will allow use it as a crib
        with:
          regex: '^\d{4}.+'
          ignore: main
          min_length: 5
          max_length: 45
